export const defaultValues = {
    nombre: '',
    descripcion: '',
    slug: '',
    id_pais: 0,
    id_departamento: 0,
    id_municipio: 0,
    id_distrito: 0,
    fecha_inicio: '',
    fecha_fin: '',
    capacidad: 0,
    id_categoria: 0,
    imagen: '',
    localidad: '',
    direccion: '',
    es_online: false,
    es_silla_numerada: false,
    cantidad_asistentes: 0,
    meet_url: '',
    archivos: [],
}